---
development:
  realms:
    apdm:
      host: checkpoint.dev
      god_session: abc

test:
  realms:
    apdm:
      host: checkpoint.dev
      god_session: abc

staging:
  realms:
    apdm:
      host: response.staging.o5.no
      god_session: xyz

production:
  realms:
    apdm:
      host: amedia.o5.no
      god_session: xyz
